//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShopASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART_DETAIL
    {
        public int id_cart_detail { get; set; }
        public int id_cart { get; set; }
        public int id_product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual CART CART { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
