//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShopASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.CART_DETAIL = new HashSet<CART_DETAIL>();
        }
    
        public int id_product { get; set; }
        public string name_product { get; set; }
        public int id_cate { get; set; }
        public Nullable<double> price { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> top_hot { get; set; }
        public string more_image { get; set; }
        public int quantity { get; set; }
        public string meta_title { get; set; }
        public string detail { get; set; }
        public Nullable<double> promotion_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_DETAIL> CART_DETAIL { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
